name: sport
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 3.0.1+100
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  event_bus: ^1.0.1
  image_picker: 0.6.6+1
  image_crop: 0.3.1
  flutter_image_compress: 0.6.3
  # 图片本地保存
  image_gallery_saver: 1.2.2
  flutter_cupertino_date_picker: 1.0.24
  url_launcher: 5.4.10
  # 本地存储
  shared_preferences: 0.5.7+3
  fluttertoast: 3.1.3
  dio: 3.0.8
  # 日期格式化
  intl: 0.16.1
  path:  1.6.4
  #path:  1.8.0-nullsafety
  path_provider: 1.5.1
  device_info :  0.4.1+4
  package_info: 0.4.0+3
  permission_handler: '3.2.0'
  #加密
  cipher2: 0.3.5 #只允许
  fluwx: 2.1.0
  #密码输入框
  pin_input_text_field: 2.1.0
  #全屏适配
  flutter_screenutil: 1.0.2
  #banner
  flutter_swiper: 1.1.4
  connectivity: 0.4.8
  #文字转拼音
  lpinyin: 1.0.7
  #android apk 安装
  install_plugin: 2.0.1
  #刷新
  flutter_easyrefresh: 2.0.4
  #视频播放
  video_player: 0.10.11+1
  #markdwon富文本框
  flutter_markdown: 0.4.1
  html2md: 0.5.1
  #极光推送
  jpush_flutter: #会导致拉到最新的版本
    path: "../dependencies/jpush-flutter-plugin-8c69e1041ec444773c57d742278daa32aa665c2a"
#    git:
#      url: https://github.com/jpush/jpush-flutter-plugin.git
#      ref: master
  #支付宝
  tobias: 1.2.0
  #gongle 字体加载
  google_fonts: 0.2.0
  imei_plugin: 1.1.6
  # Shimmer 闪烁（骨架屏使用）
  shimmer: 1.0.1
  flutter_toolplugin:
    path: "../dependencies/FlutterNativeUtil-e1a65e4013ee816c94609d86b9bbf6d34e686720"
#    git:
#     url: https://github.com/asanant/FlutterNativeUtil.git
  webview_flutter: 0.3.22
  extended_nested_scroll_view:
    path: "../dependencies/extended_nested_scroll_view-43dae31b57a1998df460c942450644ae9a68acd0"
#    git:
#      url: https://github.com/fluttercandies/extended_nested_scroll_view.git #会导致拉到最新版的插件
  #华为推送
  flutter_plugin_huawei_push:
    path: "../dependencies/flutter_plugin_huawei_push"

  #    git:
#      url: ssh://git@wbs-git:1300/git/flutter/plugin
#      path: flutter_plugin_huawei_push
  #某公司一键登录Sdk
  flutter_phone_login:
    path: "../dependencies/flutter_phone_login"
#    git:
#      url: ssh://git@wbs-git:1300/git/flutter/plugin
#      path: flutter_phone_login
  cached_network_image: 2.0.0
  #图表
  syncfusion_flutter_charts: 18.1.48
  #震动
  flutter_vibrate: 1.0.0
  web_socket_channel: 1.1.0
  audioplayers: 0.15.1
  sprintf: 4.0.0
#  services: ^0.0.1
  flutter_inappwebview: 3.4.0
  provider: 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#  fonts:
#    - family: robotoFontStyle
#      fonts:
#      - asset: assets/fonts/SourceHanSansCN.otf
  assets:
    - assets/
    - assets/images/
    - assets/animationImages/
    - assets/video/
    - assets/audio/
    - assets/html/
    - assets/images/ic_diamond.png
    - assets/images/ic_play.png
    - assets/images/ic_gift.png
    - assets/images/ic_giftBag.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
